#!/bin/bash

set -ex

wallpaperdir="/home/$(whoami)/Pictures/Wallpapers"
datefile="/home/$(whoami)/.wallsw"
thisday=$( date +%j )
wallfiles=($wallpaperdir/**/*)
#randompic=`printf "%s\n" "${wallfiles[RANDOM % ${#wallfiles[@]}]}"`
randompic=`find $wallpaperdir -not -path "$wallpaperdir/.git/*" | sort -R | tail -1`
echo $randompic > ~/.wallpaper

PID=$(pgrep xfce4-session)
export DBUS_SESSION_BUS_ADDRESS=$(grep -z DBUS_SESSION_BUS_ADDRESS /proc/$PID/environ|cut -d= -f2-)

MONITOR=${1:-0}
PROPERTY="/backdrop/screen0/monitoreDP-1/workspace0"

function set_desktop {
    date +%j > "$datefile"
    xfconf-query -c xfce4-desktop -p $PROPERTY/last-image --set $randompic
}

if [ -f "$datefile" ]
then
    lastday=$( cat "$datefile" )
    if [ "$lastday" != "$thisday" ]
    then
      set_desktop
    fi
else
  set_desktop
fi
